name: Deploy to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm packages
        run: npm install

      - name: Cleanup unnecessay files
        run: |
          rm -rf .g* build
          rm .??* *.md *.json Procfile

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: uncivserver
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_53127F4E211C4742B16BB8929AEC973C }}
          package: .
